### ISSUE TITLE
Serve at location other than / for rootpath

### ISSUE THREAD

**Issue by sullivtr** [gin-contrib/static#11]
Hello, I want to run my app in a docker-compose network with a reverse proxy. Right now everything works fine if I use static this way: 
`r.Use(static.Serve("/", static.LocalFile("/tmp", true)))` for example.

But if I try to do this:
`r.Use(static.Serve("/someotherpath", static.LocalFile("/tmp", true)))`
It does not return a 404, but it also does not find all of the static files if I hit `localhost:3000/someotherpath` the same way as when I use "/". It simply returns blank html. 

Is there a correct way to make this middleware serve the files at a different root path?

**Comment by JoshKCarroll** [comment]
After several hours running around on this issue today, I found that it is now supported in gin proper.

e.g.

`r.StaticFS("/someotherpath", gin.Dir("/tmp", true))`

**Comment by sullivtr** [comment]
I forgot about this for a while. But you are correct @JoshKCarroll, if you just use `router.Static("/someotherpath", "/path/to/static/file/dir")` it works great. Just does not work when using the middleware. 
Closing the issue
